server:
  port: ${PORT:8080}

ecommerce:
  costs:
    costPerDelivery: ${COST_PER_DELIVERY:10}
    costPerProduct: ${COST_PER_PRODUCT:1}
    fixedCost: ${FIXED_COST:2.99}

logging:
  config: classpath:log-config/logback.xml